import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import StoreProvider from "./StoreProvider";

import "sweetalert2/src/sweetalert2.scss";
const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
     
              <StoreProvider>
                <div className="flex flex-col justify-between h-[100vh]">
                  <div>
                    <Header />
                    {children}
                  </div>
                  <Footer />
                </div>
              </StoreProvider>
   
        </main>
      </body>
    </html>
  );
}
